### ISSUE TITLE
Regression when migrating from 0.9.3 to 0.9.7

### ISSUE THREAD

**Issue by tkruse** [uweschaefer/wicket-modelfactory#3]
When running our unit tests, we get:
```
java.lang.NoSuchMethodError: org.apache.wicket.request.cycle.RequestCycle.setMetaData(Lorg/apache/wicket/MetaDataKey;Ljava/lang/Object;)Lorg/apache/wicket/request/cycle/RequestCycle;
	at org.wicketeer.modelfactory.RequestCycleLocal.set(RequestCycleLocal.java:76)
	at org.wicketeer.modelfactory.RequestCycleLocalFrom.set(RequestCycleLocalFrom.java:57)
	at org.wicketeer.modelfactory.ModelFactory.from(ModelFactory.java:291)
	at accounts.AddressEditPanel.createStreetAndNumber(AddressEditPanel.java:80)
```

This exception looks dodgy, involving code paths that don't seem to have changed since 0.9.3, maybe jar was compiled differently?

**Comment by tkruse** [comment]
btw, cool that you are on github now. I notice you have no LICENSE file. This is recommended for github. I know there are file headers in the source indicating Apache License 2, but a LICENSE file is still nicer.

**Comment by tkruse** [comment]
0.9.4 also works, btw.

**Comment by uweschaefer** [comment]
thanks for reporting, will look into it.

**Comment by uweschaefer** [comment]
the only noticeable change was shifting the dependency to wicket-core from 6.0.0 to [6.0.0).
i changed it temporarily to [6.0.0,7.0.0). could you please rerun, or (better share) your tests, so that i can reproduce this?

**Comment by uweschaefer** [comment]
License file added

**Comment by tkruse** [comment]
will try to reproduce tomorrow.

**Comment by tkruse** [comment]
The bug reproduced instantly with a new quickstart project:

```
git clone https://github.com/tkruse/modelfactory-bug
mvn test
```

I don't know what you mean with "i changed it temporarily to [6.0.0,7.0.0)" Does that mean I should build modelfactory from source and try again? Hopefully you can reproduce the bug using the quickstart yourself, would be easier.

**Comment by uweschaefer** [comment]
cool will look into it.

**Comment by uweschaefer** [comment]
Ok, stupid me.

using [6.0.0,7.0.0) still is too wide, because 7.0.0-M* is still part of this range. I changed it to 6.99 to express that wicket-modelfactory (in its current state) is only compatible with the 6.* branch of Wicket.

There will be a seperate release for Wicket7, and another on faciliating java8 lambdas over the hacky lambda4j that was necessary before.

thanks!

**Comment by uweschaefer** [comment]
0.9.8 is currently staging in maven central

**Comment by jan-krakora** [comment]
Hi @uweschaefer, it's quite a wlile since you closed this issue. Are you plannig to release the wicket-modelfactory for the Wicket 7 soon?

**Comment by uweschaefer** [comment]
very busy currently, expect something in march.
